// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
	"time"
)

type Message struct {
	ID            int64     `json:"id"`
	UserID        string    `json:"userID"`
	ToPhoneNumber string    `json:"toPhoneNumber"`
	CreatedAt     time.Time `json:"createdAt"`
	Content       string    `json:"content"`
}

type PhoneNumber struct {
	ID          int64          `json:"id"`
	PhoneNumber string         `json:"phoneNumber"`
	Location    sql.NullString `json:"location"`
	UserID      string         `json:"userID"`
	CreatedAt   time.Time      `json:"createdAt"`
}

type User struct {
	ID           sql.NullInt64  `json:"id"`
	UserName     string         `json:"userName"`
	PhoneNumber  string         `json:"phoneNumber"`
	Location     sql.NullString `json:"location"`
	TypeOfDevice sql.NullString `json:"typeOfDevice"`
	CreatedAt    time.Time      `json:"createdAt"`
}
